Add mistral h100 truss
basetenlabs/truss-examples pull request #189
Opened 2024-02-07 16:54 UTC by pankajroark

The trt llm template wants to update a bunch of models, I haven't applied those changes here, so ci would fail. Will resolve that offline with @aspctu

2024-02-07 18:29 UTC, pankajroark commented
Main things to review here are changes to generate.yaml and the very  minor updates to READMEs, rest is generate via trt-llm template.

2024-02-08 00:52 UTC, joostinyi requested changes
Requesting changes due to the resource requests. We have some inflight work from @aspctu in the truss repo that should help with this code duplication problem

2024-02-08 00:52 UTC, joostinyi commented on mistral/mistral-7b-instruct-chat-trt-llm-h100/README.md
> +**Warning: This example is only intended for usage on a single A100, changing your resource type for this deployment will result in unsupported behavior**
revise copy to account for H100

2024-02-08 00:52 UTC, joostinyi commented on mistral/mistral-7b-instruct-chat-trt-llm-h100/config.yaml
> +  use_gpu: true
Revise to use H100

2024-02-08 00:52 UTC, joostinyi commented on mistral/mistral-7b-instruct-chat-trt-llm-h100/config.yaml
> +  num_workers: 2
Let's make a note to drop this `num_workers` configuration from this example once https://github.com/basetenlabs/truss/pull/801 is in

2024-02-08 00:52 UTC, joostinyi commented on mistral/mistral-7b-instruct-chat-trt-llm-h100/config.yaml
> +- transformers==4.34.1
I've had some issues with this version of transformers with mistral tokenizer in practice with regards to some special tokens (see this other [example](https://github.com/basetenlabs/truss-examples/blob/f5f44701d62110875802e80c99fa1abe5223b08e/mistral/mistral-7b-instruct-chat-trt-llm/config.yaml#L21C3-L21C23) with pin to `4.35.0`)

2024-02-08 06:21 UTC, pankajroark commented on mistral/mistral-7b-instruct-chat-trt-llm-h100/config.yaml
> +  use_gpu: true
good catch!

2024-02-08 06:29 UTC, pankajroark commented
Very useful review, all comments should be taken care of now.

2024-02-08 18:14 UTC, joostinyi approved these changes
LGTM

2024-02-08 18:15 UTC, merged